    name: Angular SSR Build

    on:
      push:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '22.15.1'

          - name: Install Dependencies
            run: npm ci
          - name: Install Angular CLI
            run: npm install -g @angular/cli
          - name: Build Angular SSR Application
            run: ng build --configuration production
            env:
              NODE_ENV: production
          - name: Commit files
            id: commit
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "github-actions"
              git add -f dist/
              if [-z "$(git status --porcelain)"]; then
                echo "::set-output name=push::false"
              else
                git commit -m "Auto add build files" -a
                echo "::set-output name=push::true"
              fi
            shell: bash
          - name: Push changes
            if: steps.commit.outputs.push == 'true'
            uses: ad-m/github-push-action@master
            with:
                 github_token: ${{ secrets.GITHUB_TOKEN }}